config/routes.rb
Rails.application.routes.draw do
  resource :cart, only: [:edit, :update, :destroy]
  resources :line_items, only: [:create, :update, :destroy]
  resources :orders, only: [:new, :create, :show]

  get '/shop' => "storefront#index"

  get '/about' => "storefront#about"

  devise_for :users
  namespace :admin do
    resources :products
    resources :brands
    resources :categories
  end

  root 'storefront#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :brand
  belongs_to :category
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

  has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100#" }, :default_url => "placeholder_:style.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates_presence_of :name, :price, :quantity, :description, :brand, :category
  validates_numericality_of :price, greater_than_or_equal_to: 0.01
  validates_numericality_of :quantity, greater_than_or_equal_to: 0

  def self.search_by_name_or_description(string)
  	where("name LIKE ? OR description LIKE ?", "%#{string}%", "%#{string}%")
  end

  private
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items Present')
        return false
      end
    end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_url(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_product_url(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :brand_id, :category_id, :avatar)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :brand_id, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin, @product]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :quantity %>
    <%= f.input :description %>
    <%= f.association :brand %>
    <%= f.association :category %>
    <%= f.input :avatar, as: :file, label: "Upload A Product Image" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_product_url(@product) %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Products<p id="new"><%= link_to '<i class="fa fa-plus fa-fw"></i>Add Product'.html_safe, new_admin_product_path %></p></h1>

<div class="container-fluid">
  <div class="panel panel-default">
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Description</th>
            <th>Brand</th>
            <th>Category</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @products.each do |admin_product| %>
            <tr>
              <td><%= image_tag admin_product.avatar.url (:thumb) %></td>
              <td class="vert-align"><%= admin_product.name %></td>
              <td class="vert-align"><%= number_to_currency admin_product.price %></td>
              <td class="vert-align"><%= admin_product.quantity %></td>
              <td class="vert-align"><%= admin_product.description %></td>
              <td class="vert-align"><%= admin_product.brand.name %></td>
              <td class="vert-align"><%= admin_product.category.name %></td>
              <td class="vert-align text-center">
                <ul>
                  <li><button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#myModal_<%= admin_product.id %>"><i class="fa fa-file-text-o"></i></button></li>
                  <li><%= link_to '<i class="fa fa-pencil-square-o"></i>'.html_safe, edit_admin_product_path(admin_product), class: "btn btn-warning btn-sm" %></li>
                  <li><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, admin_product_path(admin_product), class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></li>
                </ul>
              </td>
            </tr>

            <!-- Modal -->
            <div class="modal fade" id="myModal_<%= admin_product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title text-center" id="myModalLabel"><%= admin_product.name %></h4>
                  </div>
                  <div class="modal-body text-center">
                    <p><%= image_tag admin_product.avatar.url (:medium) %></p>
                    <h3><%= number_to_currency admin_product.price %></h3>
                    <p><%= admin_product.description %></p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-xs-10 col-xs-offset-1">
  <div class="text-center" id="image">
    <%= image_tag @product.avatar.url (:medium)%>
  </div>

  <p class="text-center">
    <strong><%= @product.name %></strong>
  </p>

  <p class="text-center" id="price">
    <%= number_to_currency @product.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= @product.quantity %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @product.description %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= @product.brand.name %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @product.category.name %>
  </p>

  <%= link_to 'Edit', edit_admin_product_path(@product) %> |
  <%= link_to 'Back', admin_products_path %>
</div>