config/routes.rb
Rails.application.routes.draw do
  resource :cart, only: [:edit, :update, :destroy]
  resources :line_items, only: [:create, :update, :destroy]
  resources :orders, only: [:new, :create, :show]

  get '/shop' => "storefront#index"

  get '/about' => "storefront#about"

  devise_for :users
  namespace :admin do
    resources :products
    resources :brands
    resources :categories
  end

  root 'storefront#index'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/shop">
        <%= image_tag("brand_image.png", height: '25', width: '150', alt: 'Star Gear') %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
      <%= render 'layouts/navbar_links' %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar_links.html.erb
<ul class="nav navbar-nav">
	<li><%= link_to 'Shop', shop_path %></li>
	<li class="dropdown">
  	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
    	<ul class="dropdown-menu">
    		<% Category.all.each do |category| %>
      			<li><%= link_to category.name.capitalize, shop_path(category_id: category.id) %></li>
      		<% end %>
      		<li class="divider"></li>
      		<li><%= link_to "All Products", shop_path %></li>
      </ul>
  </li>
	<li><%= link_to 'About', about_path %></li>
</ul>

<ul class="nav navbar-nav navbar-right">
	<% if user_signed_in? %>
		<li><%= link_to('My Account', edit_user_registration_path) %></li>
		<li><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></li>
	<% else %>
		<li><%= link_to('Login', new_user_session_path) %></li>
		<li><%= link_to('Register', new_user_registration_path) %></li>
	<% end %>

	<li class="dropdown">
  	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
    	<ul class="dropdown-menu">
      	<li><%= link_to "Categories", admin_categories_path %></li>
        <li><%= link_to "Brands", admin_brands_path %></li>
        <li><%= link_to "Products", admin_products_path %></li>
      </ul>
  </li>
  <% if session[:cart_id] %>
  <li><%= link_to fa_icon('shopping-bag', text: 'Cart'), edit_cart_path(session[:cart_id]) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StarGear</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon_brand.ico' %>
</head>
<body>
	<%= render 'layouts/navbar' %>

	<div class="container-fluid">
		<%= yield %>
	</div>
</body>
</html>